// src/ui/Structure/components/ComponentStructureNode.vue
<script setup lang="ts">
import { ref } from 'vue';
import StructureNode from './StructureNode.vue';
import PropValueShort from './PropValueShort.vue';
import type { DeclUITemplateComponentElement } from '@/types/ui/template';
import TemplateStructure from './TemplateStructure.vue';

const { component } = defineProps<{ component: DeclUITemplateComponentElement }>()

const expanded = ref<boolean>(false)
</script>

<template>
  <StructureNode v-model:expanded="expanded">
    <template #header>
      <span class="header">
        {{component.name}}
        <template v-for="(value, name) in component.props" :key="name">
          <span>
            {{name}}=<PropValueShort :value />
          </span>{{' '}}
      </template>
      </span>
    </template>
    <template #default>
      <TemplateStructure :template="component.children" />
    </template>
  </StructureNode>
</template>

<style scoped>
.header {
  color: green;
}
</style>

// src/ui/Structure/components/ComponentStructureNode/index.tsx
import { FC, useState } from "react"
import StructureNode from "../StructureNode"
import { renderPropValueShort, renderTemplateStructure } from "../../util"
import { DeclUITemplateComponentElement } from "../../../../types/ui/template"

export type ComponentStructureNodeProps = {
  component: DeclUITemplateComponentElement
}

const ComponentStructureNode: FC<ComponentStructureNodeProps> = ({ component }) => {
  const [expanded, setExpanded] = useState<boolean>(true)
  return (
    <StructureNode
      expanded={expanded}
      onToggleExpanded={setExpanded}
      header={
        <span>
          {component.component.name}{" "}
          {Object.entries(component.props).map(([name, value]) => (
            <span>
              {name}={renderPropValueShort(value)}
            </span>
          ))}
        </span>
      }
    >
      {renderTemplateStructure(component.children)}
    </StructureNode>
  )
}

export default ComponentStructureNode
