// src/ui/Structure/components/NativeStructureNode.vue
<script setup lang="ts">
import { ref } from 'vue';
import StructureNode from './StructureNode.vue';
import type { DeclUITemplateNativeElement } from '@/types/ui/template';
import PropValueShort from './PropValueShort.vue';

const { element } = defineProps<{
  element: DeclUITemplateNativeElement
}>();

const expanded = ref(false)
</script>

<template>
  <StructureNode v-model:expanded="expanded">
    <template #header>
      <span>
        &lt;{{element.name}}
        <template v-for="(value, name) in element.attrs" :key="name">
          <span>
            {{name}}=<PropValueShort :value />
          </span>{{' '}}
        </template>
        {{!expanded ? ".../" : element.children == null ? "/" : ''}}&gt;
      </span>
    </template>
    <template #default>
      <TemplateStructure :template="element.children" />
    </template>
  </StructureNode>
</template>

// src/ui/Structure/components/NativeStructureNode/index.tsx
import { FC, useState } from "react"
import StructureNode from "../StructureNode"
import { renderPropValueShort, renderTemplateStructure } from "../../util"
import React from "react"
import { DeclUITemplateNativeElement } from "../../../../types/ui/template"

export type NativeStructureNodeProps = {
  element: DeclUITemplateNativeElement
}

const NativeStructureNode: FC<NativeStructureNodeProps> = ({ element }) => {
  const [expanded, setExpanded] = useState<boolean>(true)
  return (
    <StructureNode
      expanded={expanded}
      onToggleExpanded={setExpanded}
      header={
        <span>
          &lt;{element.name}{" "}
          {Object.entries(element.attrs).map(([name, value]) => (
            <React.Fragment key={name}>
              <span>
                {name}={renderPropValueShort(value)}
              </span>{" "}
            </React.Fragment>
          ))}
          {!expanded ? ".../" : element.children == null ? "/" : undefined}&gt;
        </span>
      }
    >
      {renderTemplateStructure(element.children)}
    </StructureNode>
  )
}

export default NativeStructureNode
